name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar o repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Java (SonarQube Scanner precisa do Java)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Instalar o SonarQube Scanner
      - name: Install SonarQube Scanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.9.2.68714-linux.zip
          unzip sonar-scanner-cli-4.9.2.68714-linux.zip
          mv sonar-scanner-4.9.2.68714-linux sonar-scanner

      # 4. Rodar análise SonarQube
      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./sonar-scanner/bin/sonar-scanner \
          -Dsonar.projectKey=ToDoApp \
          -Dsonar.host.url=https://sonarcloud.io/project/overview?id=LEI-111637_ToDoApp \
          -Dsonar.login=$SONAR_TOKEN
